apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ling-shu-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - host: ling-shu.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ling-shu-api
                port:
                  name: http

