apiVersion: v1
kind: Secret
metadata:
  name: ling-shu-secret
type: Opaque
stringData:
  LING_SHU_MYSQL_DSN: "root:change-me@tcp(mysql.default.svc.cluster.local:3306)/ling_shu?charset=utf8mb4&parseTime=true&loc=Local"
  LING_SHU_JWT_SECRET: "change-me"
  LING_SHU_DSN_SECRET: "change-me-32-bytes-minimum"
  LING_SHU_REDIS_PASSWORD: ""
  LING_SHU_ALIYUN_API_KEY: ""
  LING_SHU_ALIYUN_ACCESS_KEY_ID: ""
  LING_SHU_ALIYUN_ACCESS_KEY_SECRET: ""
  LING_SHU_ALIYUN_NLS_APP_KEY: ""

